### ISSUE TITLE
Installation Manual?

### ISSUE THREAD

**Issue by ryanrrinport** [glidernet/diy-tracker#19]
Hi just wondering if there's any instructions for this? I'm using a TTGO T-beam and I'm in Canada so it's the 915 band.

**Comment by pjalocha** [comment]
Please check the project for the ESP32 CPU: https://github.com/pjalocha/esp32-ogn-tracker
use the T-Beam_v10.cfg file of another depending on your exact hardware.
If you have issues, please contact me.

**Comment by ryanrrinport** [comment]
awesome thank you!
